### PR TITLE
Fix check_authorized_users() and add some basic tests

### LINKED ISSUE #51: Add tests for `check_changes_for_autoapproval` and `check_authorized_users`
Definition of done:

- Test that confirms each function raises no error on valid changes to `model-output`
- Tests that confirm `check_changes_for_autoapproval` errors informatively when:
  - no changed files
  - changed files outside `model-output`
  - changes inside `model-output` by a user not authorized to change anything in `model-output`
  - changes inside `model-output` by a user not authorized to change _some things in `model-output`_ but not what they actually changed

Other tests as appropriate.

### PR DESCRIPTION
**Pull request by sbidari**
Fixes bug introduced by me in #224 and adds some tests
closes #51

### CODE REVIEW

File: R/check_authorized_users.R [hunk 1]
```diff
@@ -27,24 +27,28 @@ check_authorized_users <- function(
   checkmate::assert_string(base_hub_path)
 
   model_metadata <- hubData::load_model_metadata(base_hub_path) |>
+    dplyr::select("model_id", "designated_github_users") |>
     dplyr::mutate(is_model_dir = TRUE) |>
     dplyr::rename(dir = "model_id")
```
Comment (sbidari) [inline R/check_authorized_users.R]:
```suggestion
    dplyr::rename(dir = "model_id") |> 
    dplyr::distinct()
```

**Review by dylanhmorris — APPROVED** [review]
Thanks @sbidari! Nice to avoid the unnest --> summarize anyway

For future reference: now that they exist, suggest using base anon functions (e.g. `\(var) var + 1`, `\(x, y) x + y`) in place of purrr-style anon functions (`~ .x + 1`) as I think they're almost as concise and more readable
